# Generated by Django 3.2 on 2021-05-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(help_text='Introduzca su nombre aquí', max_length=100)),
                ('Apellidos', models.CharField(max_length=100)),
                ('No_of_adults', models.IntegerField()),
                ('no_of_children', models.IntegerField()),
                ('Identity_no', models.CharField(max_length=100)),
                ('Room_code', models.IntegerField()),
                ('No_of_nights', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='guest',
        ),
    ]
